spring.application.name=basecamp
# ???? ??
server.port=8888
server.servlet.session.tracking-modes=cookie
# DB ?? ??
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://bcyeon.click:9306/basecamp?characterEncoding=UTF-8&serverTimezone=KST
spring.datasource.username=choyeon
spring.datasource.password=1234!
# Mybatis xml ?? ?? ??
mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml

# spring.mvc.static-path-pattern=/static/**
# spring.resources.static-locations=classpath:/static/

# ?? ??? ??? ??? ?? ?? 3?? ??
spring.datasource.hikari.maximum-pool-size=3

# ?? ??? ?? ??
spring.servlet.multipart.max-file-size = 100MB
spring.servlet.multipart.max-request-size = 100MB

# ?? ????
server.servlet.session.timeout=0

# kakao pay SECRET_KEY
api.key=DEV730F951F604BE30F5361EEAF5AA85EB506E1F
